// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Legis.Votaciones.Domain.Models
{
    public partial class Candidatos
    {
        public Candidatos()
        {
            EleccionesCandidatos = new HashSet<EleccionesCandidatos>();
            ResultadosElecciones = new HashSet<ResultadosElecciones>();
        }

        public int CandidatoId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string TipoIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }

        public virtual ICollection<EleccionesCandidatos> EleccionesCandidatos { get; set; }
        public virtual ICollection<ResultadosElecciones> ResultadosElecciones { get; set; }
    }
}