// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Legis.Votaciones.Domain.Models
{
    public partial class EleccionesCandidatos
    {
        public int Id { get; set; }
        public int? EleccionId { get; set; }
        public int? CandidatoId { get; set; }

        public virtual Candidatos Candidato { get; set; }
        public virtual Elecciones Eleccion { get; set; }
    }
}