// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Legis.Votaciones.Domain.Models
{
    public partial class Elecciones
    {
        public Elecciones()
        {
            EleccionesCandidatos = new HashSet<EleccionesCandidatos>();
            ResultadosElecciones = new HashSet<ResultadosElecciones>();
        }

        public int EleccionId { get; set; }
        public string Nombre { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFinal { get; set; }
        public bool? Activa { get; set; }

        public virtual ICollection<EleccionesCandidatos> EleccionesCandidatos { get; set; }
        public virtual ICollection<ResultadosElecciones> ResultadosElecciones { get; set; }
    }
}