// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Legis.Votaciones.Domain.Models
{
    public partial class Usuarios
    {
        public int UsuarioId { get; set; }
        public string NomUsuario { get; set; }
        public string Contrasena { get; set; }
        public bool? EsInterno { get; set; }
    }
}