// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Legis.Votaciones.Domain.Models
{
    public partial class Votantes
    {
        public Votantes()
        {
            ResultadosElecciones = new HashSet<ResultadosElecciones>();
        }

        public int VotanteId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string TipoIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }

        public virtual ICollection<ResultadosElecciones> ResultadosElecciones { get; set; }
    }
}